# © Copyright IBM Corporation 2018, 2020
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Temporarily removing dist tag as not supported by power build
# dist: xenial

sudo: required
language: go

go:
  - "1.13.15"

services:
  - docker

go_import_path: "github.com/ibm-messaging/mq-container"

# cache:
#   directories:
#     - downloads

env:
  global:
    - RELEASE="r2"

jobs:
  include:
    - stage: basic-build
      if: branch != private-master AND tag IS blank
      name: "Basic AMD64 build"
      os: linux
      env:
        - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_920_ARCHIVE_REPOSITORY_DEV_AMD64
      script: bash -e travis-build-scripts/run.sh
    - stage: build
      if: branch = private-master OR tag =~ ^release-candidate*
      name: "Multi-Arch AMD64 build"
      os: linux
      env:
        - BUILD_ALL=true
        - MQ_ARCHIVE_REPOSITORY=$MQ_920_ARCHIVE_REPOSITORY_AMD64
        - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_920_ARCHIVE_REPOSITORY_DEV_AMD64
      script: bash -e travis-build-scripts/run.sh
    # - if: branch = private-master OR tag =~ ^release-candidate*
    #   name: "Multi-Arch PPC64LE build"
    #   os: linux-ppc64le
    #   env:
    #     - BUILD_ALL=true
    #     - TEST_OPTS_DOCKER="-run TestGoldenPathWithMetrics"
    #     # - MQ_ARCHIVE_REPOSITORY=$MQ_920_ARCHIVE_REPOSITORY_PPC64LE
    #     - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_920_ARCHIVE_REPOSITORY_DEV_PPC64LE
    #   script: bash -e travis-build-scripts/run.sh
    - stage: build
      if: branch = private-master OR tag =~ ^release-candidate*
      name: "Multi-Arch S390X build"
      os: linux-s390
      env:
        - BUILD_ALL=true
        - TEST_OPTS_DOCKER="-run TestGoldenPathWithMetrics"
        - MQ_ARCHIVE_REPOSITORY=$MQ_920_ARCHIVE_REPOSITORY_S390X
        - MQ_ARCHIVE_REPOSITORY_DEV=$MQ_920_ARCHIVE_REPOSITORY_DEV_S390X
      script: bash -e travis-build-scripts/run.sh
    - stage: push-manifest
      if: branch = private-master OR tag =~ ^release-candidate*
      name: "Push Manifest-list to registry"
      script: make push-manifest
before_install:
  - make install-build-deps
  - make install-credential-helper

install:
  - echo nothing

before_script: echo nothing

after_success:
  - make lint
