sudo: required
language: go

go:
  - "1.10"

services:
  - docker

go_import_path: "github.com/ibm-messaging/mq-container"

cache:
  directories:
    - downloads

jobs:
  include:
    - if: type IN (pull_request)
      env: DOCKER_DOWNGRADE="docker save -o images.tar mqadvanced-server-dev mq-dev-jms-test &&
        sudo apt-get autoremove -y docker-ce &&
        curl -fsSL \"https://apt.dockerproject.org/gpg\" | sudo apt-key add - &&
        sudo apt-add-repository \"deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -cs) main\" &&
        sudo apt-get update &&
        sudo apt-get install docker-engine=1.12.6-0~ubuntu-$(lsb_release -cs) &&
        docker load -q -i images.tar &&
        export DOCKER_API_VERSION=\"1.24\""
    - env: DOCKER_DOWNGRADE="echo nothing to be done"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl https://glide.sh/get | sh
  - sudo curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  - sudo chmod +x /usr/local/bin/dep

install:
  - echo nothing

script:
  - make deps
  - make build-devserver
  - make build-devjmstest
  - eval "$DOCKER_DOWNGRADE"
  - make test-devserver

after_success:
  - go get golang.org/x/lint/golint
  - make lint
